Timer v1.0
Danielo814/Danielo814.github.io pull request #7
Opened 2019-10-29 17:51 UTC by Danielo814

Here is the code we reviewed together last night. I have started trying to implement something similar to what we were talking about by separating functions but am still running into some issues.

2019-10-29 17:57 UTC, usmanity commented on countdown/countdown.js
> +#!/usr/bin/env node
this is not needed in a web script, only command line node files if they're running by themselves

2019-10-29 17:57 UTC, usmanity commented on countdown/countdown.js
> +// }
remove this and use git to keep your previous versions of the code

2019-10-29 17:57 UTC, usmanity commented on countdown/index.html
> +        <input id="input">
create inputs for seconds, minutes, and hours. Also, name them appropriately.

2019-10-29 21:36 UTC, usmanity requested changes

2019-10-29 21:36 UTC, usmanity commented on countdown/countdown.js
> +    return timerValue;
could this be just a one liner with a return statement?

2019-10-29 21:36 UTC, usmanity commented on countdown/countdown.js
> +    // }
remove for clarity

2019-10-29 21:36 UTC, usmanity commented on countdown/countdown.js
> +    var countdownInterval = setInterval(countDown, 1000, getValue());
I'm betting you'll run into an issue with clearing the interval like this, perhaps a single function to manage interval states might be better?

2019-10-30 21:55 UTC, Danielo814 commented on countdown/countdown.js
> +function manageInterval() {
I was trying to split this function up further. But kept getting problems when trying to set the timerValue variable outside of the function that setInterval was declared in. I took note of your comment to try to manage interval states within the same function and my thinking process was that this function is doing that, but also getting the value of the timer as well.

2019-10-30 21:55 UTC, Danielo814 commented on countdown/countdown.js
> +    return ((hours * 60 * 60) + (minutes * 60) + seconds);
This was originally a one liner, but it looked really long and confusing, so i split it up

2019-10-30 22:05 UTC, usmanity requested changes
Looking a lot better but I have found a major bug which I'll let you debug before this is considered done.

**Bug:** if I keep tapping the start button, the countdown speed increases with each button click. After about 3-4 clicks, it's counting down at double speed.

2019-10-30 22:05 UTC, usmanity commented on countdown/countdown.js
> +        } else{
nitpick: spacing

2019-10-30 22:05 UTC, usmanity commented on countdown/countdown.js
> +    window.timerValue = timerValue;
this is technically correct but it's unnecessary. I have suggestions that might help organize this better. 

1. Either use an app name like `countdownApp` or `timerApp` and have the variables set on that as properties
2. Or declare the `window.xxx` variables outside your functions like you have declared `paused` on line 1. This way you're not fudging with the window level variables inside functions.

2019-10-30 22:05 UTC, usmanity commented on countdown/countdown.js
> +    };
👍 this is a good use for a return object.

2019-10-30 22:05 UTC, usmanity commented on countdown/index.html
> +        <p id="time"></p>
for now this is fine but I'd encourage you to think about how to organize into parts that are different/similar. Like the inputs should be contained together. The buttons should live inside another container.

2019-10-30 22:05 UTC, usmanity commented on countdown/index.html
> +        <title>Timer</title>
folder is called `countdown` title is `timer`...what is it?

2019-10-30 22:05 UTC, usmanity commented on countdown/countdown.js
> +    }
Use template literals in this case, this is gnarly and will lead to issues if not already doing so: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2019-10-31 04:24 UTC, usmanity approved these changes

2019-10-31 04:24 UTC, merged

2019-10-31 04:58 UTC, jennjiang commented on timer/countdown.js
> +    var pauseButton = document.querySelector("#pauseButton");
'document.querySelector' might out of the day. Try use a jQuery selector : var pauseButton = $("#pauseButton");